# Generated by Django 5.2.12 on 2026-03-13 02:35

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.CreateModel(
            name='CanonicalMembershipTier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_tier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_tier_name', models.TextField(unique=True)),
                ('tier_family', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'canonical_membership_tiers',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('website', models.TextField(blank=True, null=True)),
                ('domain', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='FieldSourcePriority',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field_source_priority_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.TextField()),
                ('source_system', models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32)),
                ('priority_rank', models.IntegerField()),
            ],
            options={
                'db_table': 'field_source_priorities',
                'constraints': [models.UniqueConstraint(fields=('field_name', 'source_system'), name='field_source_priorities_field_source_unique'), models.UniqueConstraint(fields=('field_name', 'priority_rank'), name='field_source_priorities_field_rank_unique'), models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='field_source_priorities_source_system_valid')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_relationship_type', models.CharField(choices=[('individual', 'Individual'), ('corporate_seat', 'Corporate Seat'), ('complimentary', 'Complimentary'), ('partner', 'Partner'), ('sponsor', 'Sponsor'), ('internal', 'Internal'), ('staff', 'Staff')], default='individual', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('past_due', 'Past Due'), ('complimentary', 'Complimentary'), ('manual', 'Manual'), ('suspended', 'Suspended'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('payment_method_type', models.CharField(choices=[('stripe_auto', 'Stripe Auto'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('manual_override', 'Manual Override'), ('comped', 'Comped'), ('unknown', 'Unknown')], default='manual_override', max_length=24)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_currency', models.TextField(default='JPY')),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_reason', models.TextField(blank=True, null=True)),
                ('list_price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billing_frequency', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time'), ('custom', 'Custom')], max_length=16, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('amount_last_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source_of_truth', models.TextField(blank=True, null=True)),
                ('relationship_strength', models.CharField(blank=True, choices=[('core', 'Core'), ('active', 'Active'), ('peripheral', 'Peripheral'), ('dormant', 'Dormant'), ('prospect', 'Prospect')], max_length=16, null=True)),
                ('review_required', models.BooleanField(default=False)),
                ('canonical_tier', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='memberships', to='core.canonicalmembershiptier')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.organization')),
            ],
            options={
                'db_table': 'memberships',
            },
        ),
        migrations.CreateModel(
            name='MergeAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_type', models.CharField(choices=[('auto_merge', 'Auto Merge'), ('manual_merge', 'Manual Merge'), ('split', 'Split'), ('tier_remap', 'Tier Remap'), ('field_override', 'Field Override'), ('identity_rectification', 'Identity Rectification')], max_length=32)),
                ('performed_by', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('before_json', models.JSONField()),
                ('after_json', models.JSONField()),
            ],
            options={
                'db_table': 'merge_audit_logs',
                'constraints': [models.CheckConstraint(condition=models.Q(('decision_type__in', ['auto_merge', 'manual_merge', 'split', 'tier_remap', 'field_override', 'identity_rectification'])), name='merge_audit_logs_decision_type_valid')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField()),
                ('primary_email', models.TextField(blank=True, null=True)),
                ('secondary_emails', models.JSONField(blank=True, default=list)),
                ('primary_phone', models.TextField(blank=True, null=True)),
                ('secondary_phones', models.JSONField(blank=True, default=list)),
                ('company', models.TextField(blank=True, null=True)),
                ('job_title', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('linkedin_url', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persons',
                'indexes': [models.Index(django.db.models.functions.text.Lower('primary_email'), name='idx_persons_primary_email'), django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='idx_persons_full_name_trgm', opclasses=['gin_trgm_ops'])],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source_confidence_score__gte', 0), ('source_confidence_score__lte', 100)), ('source_confidence_score__isnull', True), _connector='OR'), name='persons_source_confidence_between_0_100')],
            },
        ),
        migrations.CreateModel(
            name='MembershipSeat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership_seat_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seat_title', models.TextField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.membership')),
                ('membership_holder_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_seats_owned', to='core.person')),
                ('seat_holder_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_seats_held', to='core.person')),
            ],
            options={
                'db_table': 'membership_seats',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.person'),
        ),
        migrations.CreateModel(
            name='ExternalProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32)),
                ('source_record_id', models.TextField()),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.TextField(blank=True, null=True)),
                ('source_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error'), ('ignored', 'Ignored')], default='pending', max_length=16)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_profiles', to='core.person')),
            ],
            options={
                'db_table': 'external_profiles',
            },
        ),
        migrations.CreateModel(
            name='PersonOrganization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person_organization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.TextField(default='member')),
                ('is_primary', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='core.person')),
            ],
            options={
                'db_table': 'person_organizations',
            },
        ),
        migrations.CreateModel(
            name='ReviewQueueItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('duplicate_contact', 'Duplicate Contact'), ('unknown_tier', 'Unknown Tier'), ('conflicting_membership', 'Conflicting Membership'), ('missing_email', 'Missing Email'), ('multiple_stripe_customers', 'Multiple Stripe Customers'), ('price_anomaly', 'Price Anomaly'), ('sync_error', 'Sync Error'), ('unknown_whatsapp_identity', 'Unknown WhatsApp Identity'), ('alias_conflict', 'Alias Conflict')], max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=16)),
                ('title', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('assigned_to', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('related_external_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='core.externalprofile')),
                ('related_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='core.membership')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_queue_items', to='core.person')),
            ],
            options={
                'db_table': 'review_queue_items',
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('sync_run_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_runs',
                'constraints': [models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='sync_runs_source_system_valid'), models.CheckConstraint(condition=models.Q(('direction__in', ['inbound', 'outbound'])), name='sync_runs_direction_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['started', 'completed', 'failed'])), name='sync_runs_status_valid')],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32)),
                ('action_type', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('related_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_events', to='core.membership')),
                ('related_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_events', to='core.person')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='core.syncrun')),
            ],
            options={
                'db_table': 'sync_events',
            },
        ),
        migrations.CreateModel(
            name='TierPriceSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier_price_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('list_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.TextField(default='JPY')),
                ('billing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('one_time', 'One Time'), ('custom', 'Custom')], max_length=16)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('canonical_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_schedules', to='core.canonicalmembershiptier')),
            ],
            options={
                'db_table': 'tier_price_schedules',
            },
        ),
        migrations.CreateModel(
            name='ExternalProfileAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_profile_alias_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_value', models.TextField()),
                ('alias_type', models.CharField(choices=[('display_name', 'Display Name'), ('username', 'Username'), ('group_nickname', 'Group Nickname'), ('imported_alias', 'Imported Alias'), ('manual_label', 'Manual Label')], default='display_name', max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('external_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.externalprofile')),
            ],
            options={
                'db_table': 'external_profile_aliases',
                'constraints': [models.UniqueConstraint(fields=('external_profile', 'alias_value', 'alias_type'), name='external_profile_aliases_unique_alias_per_profile'), models.CheckConstraint(condition=models.Q(('alias_type__in', ['display_name', 'username', 'group_nickname', 'imported_alias', 'manual_label'])), name='external_profile_aliases_alias_type_valid'), models.CheckConstraint(condition=models.Q(models.Q(('source_confidence_score__gte', 0), ('source_confidence_score__lte', 100)), ('source_confidence_score__isnull', True), _connector='OR'), name='external_profile_aliases_confidence_between_0_100')],
            },
        ),
        migrations.CreateModel(
            name='ExternalProfileGroupObservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_profile_group_observation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_group_id', models.TextField(blank=True, null=True)),
                ('source_group_name', models.TextField(blank=True, null=True)),
                ('observed_role', models.TextField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('source_payload_json', models.JSONField(blank=True, default=dict)),
                ('external_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_observations', to='core.externalprofile')),
            ],
            options={
                'db_table': 'external_profile_group_observations',
                'indexes': [models.Index(fields=['external_profile', 'source_group_id'], name='idx_ext_profile_group_lookup')],
            },
        ),
        migrations.CreateModel(
            name='MembershipAliasMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alias_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_system', models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32)),
                ('source_tier_name', models.TextField(blank=True, null=True)),
                ('source_product_id', models.TextField(blank=True, null=True)),
                ('source_plan_id', models.TextField(blank=True, null=True)),
                ('source_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.TextField(blank=True, default='JPY')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('canonical_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_mappings', to='core.canonicalmembershiptier')),
            ],
            options={
                'db_table': 'membership_alias_mappings',
                'indexes': [models.Index(fields=['source_system', 'source_tier_name', 'source_product_id', 'source_plan_id'], name='idx_member_alias_lookup')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='membership_alias_mappings_source_system_valid'), models.CheckConstraint(condition=models.Q(models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), ('confidence_score__isnull', True), _connector='OR'), name='membership_alias_mappings_confidence_between_0_100')],
            },
        ),
        migrations.CreateModel(
            name='MergeCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merge_candidate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('strong_signal_count', models.IntegerField(default=0)),
                ('medium_signal_count', models.IntegerField(default=0)),
                ('weak_signal_count', models.IntegerField(default=0)),
                ('explanation', models.JSONField(blank=True, default=list)),
                ('recommended_action', models.CharField(choices=[('auto_merge', 'Auto Merge'), ('review', 'Review'), ('ignore', 'Ignore')], default='review', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('merged', 'Merged'), ('ignored', 'Ignored')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('left_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_candidates_as_left', to='core.person')),
                ('right_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_candidates_as_right', to='core.person')),
            ],
            options={
                'db_table': 'merge_candidates',
                'constraints': [models.CheckConstraint(condition=models.Q(('recommended_action__in', ['auto_merge', 'review', 'ignore'])), name='merge_candidates_recommended_action_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['open', 'approved', 'rejected', 'merged', 'ignored'])), name='merge_candidates_status_valid'), models.CheckConstraint(condition=models.Q(models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 100)), ('confidence_score__isnull', True), _connector='OR'), name='merge_candidates_confidence_between_0_100'), models.CheckConstraint(condition=models.Q(('left_person', models.F('right_person')), _negated=True), name='merge_candidates_distinct_people'), models.CheckConstraint(condition=models.Q(('strong_signal_count__gte', 0)), name='merge_candidates_strong_signal_count_nonnegative'), models.CheckConstraint(condition=models.Q(('medium_signal_count__gte', 0)), name='merge_candidates_medium_signal_count_nonnegative'), models.CheckConstraint(condition=models.Q(('weak_signal_count__gte', 0)), name='merge_candidates_weak_signal_count_nonnegative')],
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['person'], name='idx_memberships_person_id'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['status'], name='idx_memberships_status'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('membership_relationship_type__in', ['individual', 'corporate_seat', 'complimentary', 'partner', 'sponsor', 'internal', 'staff'])), name='memberships_relationship_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'past_due', 'complimentary', 'manual', 'suspended', 'unknown'])), name='memberships_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('payment_method_type__in', ['stripe_auto', 'bank_transfer', 'cash', 'manual_override', 'comped', 'unknown'])), name='memberships_payment_method_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('billing_frequency__in', ['monthly', 'quarterly', 'annual', 'one_time', 'custom']), ('billing_frequency__isnull', True), _connector='OR'), name='memberships_billing_frequency_valid'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('relationship_strength__in', ['core', 'active', 'peripheral', 'dormant', 'prospect']), ('relationship_strength__isnull', True), _connector='OR'), name='memberships_relationship_strength_valid'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), ('discount_percent__isnull', True), _connector='OR'), name='memberships_discount_percent_between_0_100'),
        ),
        migrations.AddIndex(
            model_name='externalprofile',
            index=models.Index(fields=['person'], name='idx_ext_profiles_person'),
        ),
        migrations.AddIndex(
            model_name='externalprofile',
            index=models.Index(fields=['source_system', 'source_record_id'], name='idx_ext_profiles_source'),
        ),
        migrations.AddConstraint(
            model_name='externalprofile',
            constraint=models.UniqueConstraint(fields=('source_system', 'source_record_id'), name='external_profiles_source_system_source_record_id_uniq'),
        ),
        migrations.AddConstraint(
            model_name='externalprofile',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='external_profiles_source_system_valid'),
        ),
        migrations.AddConstraint(
            model_name='externalprofile',
            constraint=models.CheckConstraint(condition=models.Q(('sync_status__in', ['pending', 'synced', 'error', 'ignored'])), name='external_profiles_sync_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='reviewqueueitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_type__in', ['duplicate_contact', 'unknown_tier', 'conflicting_membership', 'missing_email', 'multiple_stripe_customers', 'price_anomaly', 'sync_error', 'unknown_whatsapp_identity', 'alias_conflict'])), name='review_queue_items_item_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='reviewqueueitem',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['low', 'medium', 'high', 'critical'])), name='review_queue_items_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='reviewqueueitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['open', 'in_progress', 'resolved', 'dismissed'])), name='review_queue_items_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='sync_events_source_system_valid'),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['success', 'error'])), name='sync_events_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='tierpriceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('billing_frequency__in', ['monthly', 'quarterly', 'annual', 'one_time', 'custom'])), name='tier_price_schedules_billing_frequency_valid'),
        ),
    ]
