# Generated by Django 5.2.12 on 2026-03-13 02:36

from django.db import migrations


CANONICAL_TIERS = [
    (
        'Core Member',
        'Paid Individual',
        'Standard paid individual membership',
    ),
    (
        'Corporate Member',
        'Paid Corporate',
        'Corporate membership with possible seats',
    ),
    ('Complimentary', 'Complimentary', 'No-cost membership'),
    ('Prospect', 'Pipeline', 'Not yet a member'),
    ('Partner', 'Special', 'Partner or sponsored relationship'),
]


FIELD_SOURCE_PRIORITIES = [
    ('email', 'stripe', 1),
    ('email', 'mailchimp', 2),
    ('email', 'luma', 3),
    ('email', 'google_sheets', 4),
    ('email', 'apple_contacts', 5),
    ('email', 'clay', 6),
    ('email', 'linkedin', 7),
    ('phone', 'whatsapp', 1),
    ('phone', 'apple_contacts', 2),
    ('phone', 'google_sheets', 3),
    ('phone', 'stripe', 4),
    ('phone', 'luma', 5),
    ('name', 'apple_contacts', 1),
    ('name', 'google_sheets', 2),
    ('name', 'stripe', 3),
    ('name', 'luma', 4),
    ('name', 'mailchimp', 5),
    ('name', 'clay', 6),
    ('name', 'linkedin', 7),
    ('name', 'whatsapp', 8),
    ('company', 'apple_contacts', 1),
    ('company', 'google_sheets', 2),
    ('company', 'clay', 3),
    ('company', 'linkedin', 4),
    ('membership_status', 'stripe', 1),
    ('membership_status', 'google_sheets', 2),
    ('membership_status', 'mailchimp', 3),
    ('membership_status', 'luma', 4),
]


def seed_reference_data(apps, schema_editor):
    canonical_tier_model = apps.get_model('core', 'CanonicalMembershipTier')
    field_source_priority_model = apps.get_model('core', 'FieldSourcePriority')

    for canonical_tier_name, tier_family, description in CANONICAL_TIERS:
        canonical_tier_model.objects.update_or_create(
            canonical_tier_name=canonical_tier_name,
            defaults={
                'tier_family': tier_family,
                'description': description,
                'is_active': True,
            },
        )

    for field_name, source_system, priority_rank in FIELD_SOURCE_PRIORITIES:
        field_source_priority_model.objects.update_or_create(
            field_name=field_name,
            source_system=source_system,
            defaults={'priority_rank': priority_rank},
        )


def unseed_reference_data(apps, schema_editor):
    canonical_tier_model = apps.get_model('core', 'CanonicalMembershipTier')
    field_source_priority_model = apps.get_model('core', 'FieldSourcePriority')

    canonical_tier_model.objects.filter(
        canonical_tier_name__in=[tier[0] for tier in CANONICAL_TIERS]
    ).delete()
    for field_name, source_system, _priority_rank in FIELD_SOURCE_PRIORITIES:
        field_source_priority_model.objects.filter(
            field_name=field_name,
            source_system=source_system,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_reference_data, unseed_reference_data),
    ]
