# Generated by Django 5.2.12 on 2026-03-13 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProfileSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_profile_snapshot_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload_json', models.JSONField(blank=True, default=dict)),
                ('normalized_payload_json', models.JSONField(blank=True, default=dict)),
                ('source_hash', models.TextField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('external_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.externalprofile')),
                ('sync_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_snapshots', to='core.syncrun')),
            ],
            options={
                'db_table': 'external_profile_snapshots',
                'indexes': [models.Index(fields=['external_profile', 'created_at'], name='idx_ext_prof_snap_created')],
            },
        ),
    ]
