# Generated by Django 5.2.12 on 2026-03-15 03:08

from django.db import migrations, models


SUBSTACK_FIELD_SOURCE_PRIORITIES = [
    ('email', 'substack', 8),
    ('name', 'substack', 9),
    ('membership_status', 'substack', 5),
]


def seed_substack_reference_priorities(apps, schema_editor):
    field_source_priority_model = apps.get_model('core', 'FieldSourcePriority')

    for field_name, source_system, priority_rank in SUBSTACK_FIELD_SOURCE_PRIORITIES:
        field_source_priority_model.objects.update_or_create(
            field_name=field_name,
            source_system=source_system,
            defaults={'priority_rank': priority_rank},
        )


def unseed_substack_reference_priorities(apps, schema_editor):
    field_source_priority_model = apps.get_model('core', 'FieldSourcePriority')

    for field_name, source_system, _priority_rank in SUBSTACK_FIELD_SOURCE_PRIORITIES:
        field_source_priority_model.objects.filter(
            field_name=field_name,
            source_system=source_system,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reviewqueue_profile_link_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='externalprofile',
            name='external_profiles_source_system_valid',
        ),
        migrations.RemoveConstraint(
            model_name='fieldsourcepriority',
            name='field_source_priorities_source_system_valid',
        ),
        migrations.RemoveConstraint(
            model_name='membershipaliasmapping',
            name='membership_alias_mappings_source_system_valid',
        ),
        migrations.RemoveConstraint(
            model_name='syncevent',
            name='sync_events_source_system_valid',
        ),
        migrations.RemoveConstraint(
            model_name='syncrun',
            name='sync_runs_source_system_valid',
        ),
        migrations.AlterField(
            model_name='externalprofile',
            name='source_system',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('substack', 'Substack'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='fieldsourcepriority',
            name='source_system',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('substack', 'Substack'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='membershipaliasmapping',
            name='source_system',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('substack', 'Substack'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='syncevent',
            name='source_system',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('substack', 'Substack'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='syncrun',
            name='source_system',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('luma', 'Luma'), ('substack', 'Substack'), ('mailchimp', 'Mailchimp'), ('google_sheets', 'Google Sheets'), ('apple_contacts', 'Apple Contacts'), ('manual_csv', 'Manual CSV'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('clay', 'Clay'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='externalprofile',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'substack', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='external_profiles_source_system_valid'),
        ),
        migrations.AddConstraint(
            model_name='fieldsourcepriority',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'substack', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='field_source_priorities_source_system_valid'),
        ),
        migrations.AddConstraint(
            model_name='membershipaliasmapping',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'substack', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='membership_alias_mappings_source_system_valid'),
        ),
        migrations.AddConstraint(
            model_name='syncevent',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'substack', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='sync_events_source_system_valid'),
        ),
        migrations.AddConstraint(
            model_name='syncrun',
            constraint=models.CheckConstraint(condition=models.Q(('source_system__in', ['stripe', 'luma', 'substack', 'mailchimp', 'google_sheets', 'apple_contacts', 'manual_csv', 'whatsapp', 'linkedin', 'clay', 'other'])), name='sync_runs_source_system_valid'),
        ),
        migrations.RunPython(
            seed_substack_reference_priorities,
            unseed_substack_reference_priorities,
        ),
    ]
