# Generated by Django 5.2.12 on 2026-03-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_externalprofile_external_profiles_source_system_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewqueueitem',
            name='item_type',
            field=models.CharField(choices=[('duplicate_contact', 'Duplicate Contact'), ('unknown_tier', 'Unknown Tier'), ('conflicting_membership', 'Conflicting Membership'), ('missing_email', 'Missing Email'), ('multiple_stripe_customers', 'Multiple Stripe Customers'), ('price_anomaly', 'Price Anomaly'), ('sync_error', 'Sync Error'), ('unknown_whatsapp_identity', 'Unknown WhatsApp Identity'), ('alias_conflict', 'Alias Conflict'), ('profile_link_review', 'Profile Link Review')], max_length=32),
        ),
    ]
